apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2 # K8s allows you to run multiple instances for high availability
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mhyderali004/cicd-backend:latest
        imagePullPolicy: Always # Forces K8s to always fetch the newest image
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL # Example for Spring Boot
          value: jdbc:mysql://mysql-service:3306/mydb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mysql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
